

EVENT_LIMIT: 100
#
server:
  port: $PORT
  ## Logging settings
logging:
  file:
    name: "eventSystem.log"
    path: "./"
  level:
    root: INFO
    org:
      springframework:
        transaction:
          interceptor: TRACE
